apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-global-httproute
  namespace: grc-team
spec:
  # Allow the global HTTPRoute namespace to reference this namespace.
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: global-api-gateway-ns
  # Allow only the grc ingress gateway Service as a backend.
  to:
  - group: ""
    kind: Service
    name: grc-istio-ingressgateway
