apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-global-httproute
  namespace: payments-team
spec:
  # Allow the global HTTPRoute namespace to reference this namespace.
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: global-api-gateway-ns
  # Allow only the payments ingress gateway Service as a backend.
  to:
  - group: ""
    kind: Service
    name: payments-istio-ingressgateway
