# Allows the global HTTPRoute (in global-api-gateway-ns) to reference
# the payments IngressGateway Service (now in payments-ingress).
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-global-httproute
  namespace: payments-ingress
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: global-api-gateway-ns
  to:
  - group: ""
    kind: Service
    name: payments-istio-ingressgateway
