apiVersion: v1
kind: Secret
metadata:
  name: retail-alertmanager-config
  namespace: istio-system
type: Opaque
stringData:
  alertmanager.yml: |
    global:
      smtp_smarthost: smtp.gmail.com:587
      smtp_from: zinawsglory@gmail.com
      smtp_auth_username: zinawsglory@gmail.com
      smtp_auth_password: REPLACE_WITH_GMAIL_APP_PASSWORD
      smtp_require_tls: true

    route:
      receiver: gmail
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 30m

    receivers:
    - name: gmail
      email_configs:
      - to: zinawsglory@gmail.com
        send_resolved: true
