---
apiVersion: v1
kind: Service
metadata:
  name: fraud-svc
  namespace: grc-team
spec:
  # type: LoadBalancer
  selector:
    app: fraud-svc
  ports:
    - name: http
      port: 6061
      targetPort: 9091
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fraud-svc
  namespace: grc-team
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-svc
  namespace: grc-team
  labels:
    app: fraud-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-svc
  template:
    metadata:
      labels:
        app: fraud-svc
    spec:
      serviceAccountName: fraud-svc
      containers:
        - name: fraud-svc
          image: nicholasjackson/fake-service:v0.26.2
          ports:
            - containerPort: 9091
          env:
            - name: LISTEN_ADDR
              value: '0.0.0.0:9091'
            - name: UPSTREAM_URIS
              value: 'http://audit-svc.grc-team.svc.cluster.local:6062'
            - name: NAME
              value: 'fraud-svc'
            - name: MESSAGE
              value: 'HelloCloudBank | GRC | fraud-svc'
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
