apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: payments-gateway
  namespace: payments-ingress
spec:
  selector:
    app: payments-istio-ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - finance.hellocloud.io
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: payments-routes
  namespace: payments-team
spec:
  hosts:
  - finance.hellocloud.io
  gateways:
  - payments-ingress/payments-gateway   # cross-namespace reference
  http:
  - match:
    - uri:
        prefix: /transactions
    route:
    - destination:
        host: transfer-svc.payments-team.svc.cluster.local
        port:
          number: 7071
